apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-example-appprod
  namespace: prometheus-example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-example-app
      app.kubernetes.io/env: prod
      app.kubernetes.io/instance: prometheus-example-app-prod
      app.kubernetes.io/component: prometheus-example-appprod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-example-app
        app.kubernetes.io/env: prod
        app.kubernetes.io/instance: prometheus-example-app-prod
        app.kubernetes.io/component: prometheus-example-appprod
    spec:
      containers:
      - image: quay.io/brancz/prometheus-example-app:v0.3.0
        name: prometheus-example-app
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
            ephemeral-storage: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
            ephemeral-storage: 1Gi
---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-example-app
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/name: prometheus-example-app
    app.kubernetes.io/env: prod
    app.kubernetes.io/instance: prometheus-example-app-prod
    app.kubernetes.io/component: prometheus-example-appprod
  name: prometheus-example-appprod
  namespace: prometheus-example-app
spec:
  podMetricsEndpoints:
  - port: web
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-example-app
      app.kubernetes.io/env: prod
      app.kubernetes.io/instance: prometheus-example-app-prod
      app.kubernetes.io/component: prometheus-example-appprod