- id: apps/v1:Deployment:prometheus-example-app:prometheus-example-appprod
  type: Kubernetes
  attributes:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
        name: prometheus-example-appprod
        namespace: prometheus-example-app
    spec:
        replicas: 1
        selector:
            matchLabels:
                app.kubernetes.io/component: prometheus-example-appprod
                app.kubernetes.io/env: prod
                app.kubernetes.io/instance: prometheus-example-app-prod
                app.kubernetes.io/name: prometheus-example-app
        template:
            metadata:
                labels:
                    app.kubernetes.io/component: prometheus-example-appprod
                    app.kubernetes.io/env: prod
                    app.kubernetes.io/instance: prometheus-example-app-prod
                    app.kubernetes.io/name: prometheus-example-app
            spec:
                containers:
                    - image: quay.io/brancz/prometheus-example-app:v0.3.0
                      name: prometheus-example-app
                      ports:
                        - containerPort: 8080
                          name: web
                          protocol: TCP
                      resources:
                        limits:
                            cpu: 100m
                            ephemeral-storage: 1Gi
                            memory: 100Mi
                        requests:
                            cpu: 100m
                            ephemeral-storage: 1Gi
                            memory: 100Mi
  dependsOn:
    - v1:Namespace:prometheus-example-app
- id: v1:Namespace:prometheus-example-app
  type: Kubernetes
  attributes:
    apiVersion: v1
    kind: Namespace
    metadata:
        name: prometheus-example-app
- id: monitoring.coreos.com/v1:PodMonitor:prometheus-example-app:prometheus-example-appprod
  type: Kubernetes
  attributes:
    apiVersion: monitoring.coreos.com/v1
    kind: PodMonitor
    metadata:
        labels:
            app.kubernetes.io/component: prometheus-example-appprod
            app.kubernetes.io/env: prod
            app.kubernetes.io/instance: prometheus-example-app-prod
            app.kubernetes.io/name: prometheus-example-app
        name: prometheus-example-appprod
        namespace: prometheus-example-app
    spec:
        podMetricsEndpoints:
            - port: web
        selector:
            matchLabels:
                app.kubernetes.io/component: prometheus-example-appprod
                app.kubernetes.io/env: prod
                app.kubernetes.io/instance: prometheus-example-app-prod
                app.kubernetes.io/name: prometheus-example-app
