id: hashicorp:aws:aws_security_group:wordpress-example-dev
type: Terraform
attributes:
  egress:
  - description: ''
    from_port: 0
    to_port: 0
    protocol: '-1'
    cidr_blocks:
    - 0.0.0.0/0
    ipv6_cidr_blocks: null
    prefix_list_ids: null
    security_groups: null
    self: false
  ingress:
  - description: ''
    from_port: 3306
    to_port: 3306
    protocol: tcp
    cidr_blocks:
    - 0.0.0.0/0
    ipv6_cidr_blocks: null
    prefix_list_ids: null
    security_groups: null
    self: false
  name: wordpress-example-dev
extensions:
  provider: registry.terraform.io/hashicorp/aws/5.0.1
  resourceType: aws_security_group
  providerMeta:
    region: us-east-1
---
id: hashicorp:aws:aws_db_instance:wordpress-example-dev
type: Terraform
attributes:
  allocated_storage: 10
  db_subnet_group_name: default
  engine: MySQL
  engine_version: '5.7'
  identifier: wordpress-example-dev
  instance_class: db.t3.micro
  password: Kusion123456
  publicly_accessible: true
  skip_final_snapshot: true
  username: root
  vpc_security_group_ids:
  - $kusion_path.hashicorp:aws:aws_security_group:wordpress-example-dev.id
extensions:
  provider: registry.terraform.io/hashicorp/aws/5.0.1
  resourceType: aws_db_instance
  providerMeta:
    region: us-east-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: wordpress-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wordpress-example
      app.kubernetes.io/env: dev
      app.kubernetes.io/instance: wordpress-example-dev
      cluster.x-k8s.io/cluster-name: default
      app.kubernetes.io/component: wordpress-deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wordpress-example
        app.kubernetes.io/env: dev
        app.kubernetes.io/instance: wordpress-example-dev
        cluster.x-k8s.io/cluster-name: default
        app.kubernetes.io/component: wordpress-deployment
    spec:
      containers:
      - env:
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-pass
        - name: ENV_ADD_EXAMPLE
          value: wordpress-example
        - name: WORDPRESS_DB_HOST
          value: $kusion_path.hashicorp:aws:aws_db_instance:wordpress-example-dev.address
        image: wordpress:4.8-apache
        name: wordpress
        ports:
        - containerPort: 80
          name: wordpress
          protocol: TCP
        volumeMounts:
        - mountPath: /var/www/html
          name: wordpress-persistent-storage
      volumes:
      - name: wordpress-persistent-storage
        emptyDir: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: wordpress-example
---
apiVersion: v1
data:
  password: S3VzaW9uMTIzNDU2
kind: Secret
type: Opaque
metadata:
  name: mysql-pass
  namespace: wordpress-example
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress-example
spec:
  ports:
  - port: 80
  selector:
    app.kubernetes.io/name: wordpress-example
    app.kubernetes.io/env: dev
    app.kubernetes.io/instance: wordpress-example-dev
    cluster.x-k8s.io/cluster-name: default
    app.kubernetes.io/component: wordpress-deployment
  type: ClusterIP