apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleappprod
  namespace: sampleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sampleapp
      app.kubernetes.io/env: prod
      app.kubernetes.io/instance: sampleapp-prod
      cluster.x-k8s.io/cluster-name: demo-cluster-name
      app.kubernetes.io/version: v1.0.0
      app.kubernetes.io/component: sampleappprod
  template:
    metadata:
      annotations:
        owner: team-iac
      labels:
        app.kubernetes.io/name: sampleapp
        app.kubernetes.io/env: prod
        app.kubernetes.io/instance: sampleapp-prod
        cluster.x-k8s.io/cluster-name: demo-cluster-name
        app.kubernetes.io/component: sampleappprod
        app.kubernetes.io/version: v1.0.0
    spec:
      containers:
      - image: gcr.io/google-samples/gb-frontend:v4
        name: main
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
            ephemeral-storage: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
            ephemeral-storage: 1Gi
---
apiVersion: v1
kind: Namespace
metadata:
  name: sampleapp