schema AlicloudRDSAccount:
	
    account_description?: str
    
    account_name?: str
    
    account_password?: str
    
    account_type?: str
    
    db_instance_id?: str
    
    description?: str
    
    id?: str
    
    instance_id?: str
    
    kms_encrypted_password?: str
    
    kms_encryption_context?: {str:str}
    
    name?: str
    
    password?: str
    
    status?: str
    
    type?: str
