apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-leader
  namespace: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: guestbook
      app.kubernetes.io/env: prod
      app.kubernetes.io/instance: guestbook-prod
      cluster.x-k8s.io/cluster-name: demo-cluster-name
      app.kubernetes.io/component: redis-leader
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guestbook
        app.kubernetes.io/env: prod
        app.kubernetes.io/instance: guestbook-prod
        cluster.x-k8s.io/cluster-name: demo-cluster-name
        app.kubernetes.io/component: redis-leader
    spec:
      containers:
      - image: docker.io/redis:6.0.5
        name: main
        ports:
        - containerPort: 6379
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
            ephemeral-storage: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
            ephemeral-storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-follower
  namespace: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: guestbook
      app.kubernetes.io/env: prod
      app.kubernetes.io/instance: guestbook-prod
      cluster.x-k8s.io/cluster-name: demo-cluster-name
      app.kubernetes.io/component: redis-follower
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guestbook
        app.kubernetes.io/env: prod
        app.kubernetes.io/instance: guestbook-prod
        cluster.x-k8s.io/cluster-name: demo-cluster-name
        app.kubernetes.io/component: redis-follower
    spec:
      containers:
      - image: gcr.io/google_samples/gb-redis-follower:v2
        name: main
        ports:
        - containerPort: 6379
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
            ephemeral-storage: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
            ephemeral-storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: guestbook
      app.kubernetes.io/env: prod
      app.kubernetes.io/instance: guestbook-prod
      cluster.x-k8s.io/cluster-name: demo-cluster-name
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guestbook
        app.kubernetes.io/env: prod
        app.kubernetes.io/instance: guestbook-prod
        cluster.x-k8s.io/cluster-name: demo-cluster-name
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - env:
        - name: GET_HOSTS_FROM
          value: dns
        image: gcr.io/google-samples/gb-frontend:v3
        name: php-redis
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
            ephemeral-storage: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
            ephemeral-storage: 1Gi
---
apiVersion: v1
kind: Namespace
metadata:
  name: guestbook
---
apiVersion: v1
kind: Service
metadata:
  name: redis-leader
  namespace: guestbook
spec:
  ports:
  - port: 6379
  selector:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/env: prod
    app.kubernetes.io/instance: guestbook-prod
    cluster.x-k8s.io/cluster-name: demo-cluster-name
    app.kubernetes.io/component: redis-leader
---
apiVersion: v1
kind: Service
metadata:
  name: redis-follower
  namespace: guestbook
spec:
  ports:
  - port: 6379
  selector:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/env: prod
    app.kubernetes.io/instance: guestbook-prod
    cluster.x-k8s.io/cluster-name: demo-cluster-name
    app.kubernetes.io/component: redis-follower
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: guestbook
spec:
  ports:
  - port: 80
  selector:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/env: prod
    app.kubernetes.io/instance: guestbook-prod
    cluster.x-k8s.io/cluster-name: demo-cluster-name
    app.kubernetes.io/component: frontend