- id: monitoring.coreos.com/v1:PrometheusRule:default:k8s-rules
  type: Kubernetes
  attributes:
    apiVersion: monitoring.coreos.com/v1
    kind: PrometheusRule
    metadata:
        labels:
            prometheus: main
            role: alert-rules
        name: k8s-rules
        namespace: default
    spec:
        groups:
            - name: node.rules
              rules:
                - expr: |
                    sum(
                      node_memory_MemAvailable_bytes{job="node-exporter"} or
                      (
                        node_memory_Buffers_bytes{job="node-exporter"} +
                        node_memory_Cached_bytes{job="node-exporter"} +
                        node_memory_MemFree_bytes{job="node-exporter"} +
                        node_memory_Slab_bytes{job="node-exporter"}
                      )
                    ) by (cluster)
                  record: :node_memory_MemAvailable_bytes:sum
                - expr: |
                    sum(rate(node_cpu_seconds_total{job="node-exporter",mode!="idle",mode!="iowait",mode!="steal"}[5m])) /
                    count(sum(node_cpu_seconds_total{job="node-exporter"}) by (cluster, instance, cpu))
                  record: cluster:node_cpu:ratio_rate5m
