MAIN_FILE = "main.k"
CI_TEST_DIR = "ci-test"
SETTINGS_FILE = "settings.yaml"
STDOUT_GOLDEN_FILE = "stdout.golden.yaml"
KCL_FILE = "kcl.yaml"
OWNERS_FILE = "OWNERS"
HACK_DIR = "hack"
STUB_CASE = "stub_case"
EMPTY_CHANGE_LIST = "zz_default_change_list_value"
TRIGGER_ALL_TEST = "zz_all_test"

PROJECT_FILE = "project.yaml"
STACK_FILE = "stack.yaml"
KCL_FILE_SUFFIX = ".k"
KCL_MOD_FILE = "kcl.mod"
KCL_MOD_LOCK_FILE = "kcl.mod.lock"