CHANGED_PROJECTS = "CHANGED_PROJECTS"
CHANGED_STACKS = "CHANGED_STACKS"
CHANGED_PATHS = "CHANGED_PATHS"
GITHUB_OUTPUT = "GITHUB_OUTPUT"

PROJECT_FILE = "project.yaml"
STACK_FILE = "stack.yaml"
KCL_FILE_SUFFIX = ".k"
KCL_MOD_FILE = "kcl.mod"
KCL_MOD_LOCK_FILE = "kcl.mod.lock"
NAME = "name"
KUSION_CMD = "kusion"
COMPILE_CMD = "compile"

IGNORE_PROJECTS = ["example/wordpress"]
